### ISSUE TITLE
Using Ramda in TypeScript without bundling inside my app code

### ISSUE THREAD

**Issue by lcrespom** [types/npm-ramda#128]
I am writing a small web app in TypeScript and bundling the final JS with Browserify. The whole JS bundle takes 30 kb without minification.

Now I want to use a few functions of the Ramda library. If I install Ramda via npm and import it from my app code, the resulting bundle grows to more than 300 kb.

So I am loading Ramda as an independent script from `index.html`:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/ramda/0.23.0/ramda.min.js"></script>
<script src="bundle.js"></script> <!-- My small app -->
```
Now from my app code I just do:
```
declare var R;
```
And my app has access to all Ramda functions from the R global variable. However, using this approach has a major limitation: R is of type `any`, and there is no type checking available.

So I would want to do `npm install @types/ramda` in order to have all the type checking, but without having to do `npm install ramda` in order to avoid bundling Ramda code in my app.

I have tried many combinations of imports such as `import * as R from '@types/ramda'`, but I always get error messages at some stage: either TS does not compile or Browserify fails to build.

Now I could always just copy the type definitions of Ramda inside my project code... but is there a cleaner way of doing what I want? **In short, is it possible to use Ramda with type checking without bundling all its code in my app? If so, how?**

**Comment by tycho01** [comment]
The published version of `@types/ramda` is still outdated. [Apparently](https://github.com/types/npm-ramda/issues/116#issuecomment-269909153) some future improvement would facilitate publishing though until then I'm not sure how; I'll have to defer to others on that.
On importing only part of Ramda, you might find [this thread](https://github.com/ramda/ramda/issues/1968) informative.
That said, the TS import should import just `ramda` -- at that point it should pick up the types automatically.
I'm not sure it would work without a Ramda install, but just because it'd be installed wouldn't necessarily mean everything would need to get bundled. That said, I haven't personally used Browserify.

**Comment by tycho01** [comment]
I updated the version published at `typings` as per [this thread](https://github.com/types/npm-ramda/issues/132).
In Webpack they refer to grabbing only the bits you need as tree-shaking. Ramda had it own solution, see that thread above.

**Comment by tycho01** [comment]
This is now supported, see the readme.
