### ISSUE TITLE
ramda-fantasy

### ISSUE THREAD

**Issue by puffnfresh** [types/npm-ramda#130]
Would it be reasonable to have ramda-fantasy bindings in this project?

**Comment by tycho01** [comment]
Since they're technically imported from their own library rather than Ramda, I wonder if it works to import typings for that through this.
That said, I'd make a terrible bureaucrat, feel free to experiment and make PRs. If it'd need to be put into a separate thing that's something we can still do as well anyway.

**Comment by tycho01** [comment]
Related: I already tried including typings for the fantasy land data types as they technically are used within Ramda as well. That said typing those was still problematic due to current TS limitations. But that might help a bit.
That said, AFAIK ramda-fantasy would potentially be [merged](https://github.com/ramda/ramda-fantasy/issues/105) into [Sanctuary](https://github.com/sanctuary-js/sanctuary), and that's already gotten its own [typings repo](https://github.com/mnn/typings-sanctuary) as well.

**Comment by knikel** [comment]
@tycho01: I'm sorry for a bit off topic/silly/noob question here, but not sure where to ask regarding it. What TypeScript limitations do you have in mind? I'm curious to learn more regarding that. A link elsewhere will suffice. Thanks.

**Comment by tycho01** [comment]
@knikel rest assured I learned about this [only recently myself](https://github.com/fantasyland/fantasy-land/issues/140#issuecomment-263762353). :)

**Comment by knikel** [comment]
Very enlightening read. Thank you!

**Comment by tycho01** [comment]
Continuing discussion in #186.
