### ISSUE TITLE
Trying to install ramda types via typings, but ccan

### ISSUE THREAD

**Issue by AbhilashSrivastava** [types/npm-ramda#132]

**Comment by AbhilashSrivastava** [comment]
I am trying to install ramda types using ' > typings install ramda ', but by default its installing the 0.21 version. Have tried various commands and variations (for instance, changing the version manually , but it won't install the latest version).

Problem: I can't find pathSatisfies typings in the current version which i am using (0.21).

**Comment by tycho01** [comment]
Made a PR [here](https://github.com/typings/registry/pull/958). Thanks for noting this.
Out of curiosity @blakeembrey, I see it's using fixed commits; so people wouldn't like just fix the newest version to our master branch huh?

**Comment by blakeembrey** [comment]
@tycho01 Fixed commits was always a conscious decision in Typings. Sadly, it's also one of the issues I have with the NPM `@types` I'd like to solve. The reason you'd want fixed commits over automatically incrementing commits is that type definitions (especially third-party definitions) can be subject to breaking within the same semver source release. If projects automatically update, it means random CI breakages for dependents or worse, it means no one ever removes broken code because it "might break some one".

As NPM `@types` will eventually be replacing typings, my time isn't spent solving these problems anymore 😄

**Comment by tycho01** [comment]
Preventing breaking huh. Time to break it before locking us out of publishing newer versions!

**Comment by tycho01** [comment]
Made a [new one](https://github.com/typings/registry/pull/960) there. I could be misinterpreting best practice, feel free to comment.

**Comment by blakeembrey** [comment]
@tycho01 Sorry, there might have been a misunderstanding 😄  Internally with Typings, you can release whatever you want on the registry and it won't break users, it just prints a notice next time they install. It's pinned to the commit (more specifically, it's pinned to the timestamp it was added to the registry). That means you can release as many versions of `1.0.0` as you'd like, they still increment on the Typings registry and the old ones just get "hidden". (e.g. http://api.typings.org/entries/env/node/versions?deprecated=true).
