### ISSUE TITLE
Should test.ts be ok?

### ISSUE THREAD

**Issue by whitecolor** [types/npm-ramda#164]
Why in the test.ts I see so many errors?

![image](https://cloud.githubusercontent.com/assets/736697/24586372/cddf5ec2-17b8-11e7-9859-123f19bf087b.png)

**Comment by tycho01** [comment]
Yeah, this one went wrong. Things tend to get a bit tougher with partial application, which admittedly is super unfortunate since it's kind of the point in using Ramda.
I'll concede I'm not actually sure how to address this one, and I'm aware it's definitely not the only issue (though a few of the errors it throws are actually expected). I'd be open to PRs.

I've added a note on the project status (presence of errors) in the readme now.

**Comment by tycho01** [comment]
Should be largely fixed by #190. If not feel free to report back.
