### ISSUE TITLE
Curried propOr

### ISSUE THREAD

**Issue by Ramblurr** [types/npm-ramda#170]
The curried `propOr` doesn't seem to be right.

### 1st Try: `never` type

```js

  const alice = {
    age: 20,
    height: 160
  };

  const defaultZero = R.propOr(0);
  const ageOrZero = defaultZero("age", alice);

// TS errors:
// TS2345:Argument of type '"age"' is not assignable to parameter of type 'never'.
```

### 2nd Try

So I get explicit about the types

```js 
  const alice = {
    age: 20,
    height: 160,
  } as { [k: string]: number };

  const defaultZero = R.propOr<number, { [k: string]: number }, string>(0);
  const ageOrZero = defaultZero("age", alice);

// TS2345:Argument of type '{ [k: string]: number; }' is not assignable to parameter of type 'Dictionary<string>'.
//   Index signatures are incompatible.
//    Type 'number' is not assignable to type 'string'.
```

This led me to the definition of `propOr` in `index.d.ts`, which is:
```js
        propOr<T,U,K extends keyof U>(val: T): CurriedFunction2<K, Obj<K>, K|T>;
```

Two things that strike me here are:

1. Why can the return value be `K` or `T`. It should just be `T`, the value type of the dictionary
2.  `Obj<K>` is suspicious to me, because the generic param of `Obj` should be the value type, not the key type. But in this line `K` is the key type.

I changed the definition to be this, ensuring only `T` is returned and making `T` the value type of `Obj`, this compiles with the above example.

```js
        propOr<T,U,K extends keyof U>(val: T): CurriedFunction2<K, Obj<T>, T>; 
```

**Comment by tycho01** [comment]
Sorry, you appear right that part no longer makes sense, it seems to have degenerated from the original strategy still seen in `// propOr<T,U,K extends keyof U>: CurriedFunction3<T, K, U, U[K]|T>`. That said, currying does make for some challenges there -- once params 2 and 3 separate, inference by this method falls apart.

The proposed `propOr<T,U,K extends keyof U>(val: T): CurriedFunction2<K, Obj<T>, T>` still retains some of the oddities of the current version: `U` is an unbound generic, meaning `K` also loses meaning as a generic, meaning what we're left with... is essentially not much different from the strategy `propOr<T>(val: T, p: Prop, obj: Struct<any>): T` below.

One difference is you're restricting to homogenous objects, of course. That doesn't remove the need for a version without that restriction though, while I'm under the impression it also wouldn't improve inference over it. In that sense, I'm under the impression it might be redundant.
(Note, that version also has its flaws by dropping the limitation -- it's hard to achieve perfection under the information restrictions imposed by currying though...)

My suggestion would be to have that set restored to its original strategy. Would that address your use-case?

**Comment by Ramblurr** [comment]
When I comment in/out such that the original strategy is active (please verify below as I had to add the `(val: T)` to make it compile), I still get the error `Argument of type 'string' is not assignable to parameter of type 'number'.`

Original strategy: `propOr<T,U,K extends keyof U>(val: T): CurriedFunction3<T, K, U, U[K]|T>;`

But I guess I don't understand how to use the `CurriedFunction3` variety.

Given:

```js
  const alice = {
    age: 20,
    height: 160
  };

  const defaultZero = R.propOr(0);
  const ageOrZero = defaultZero("age", alice); // errors happens on the "age" bit here
```

`defaultZero` is now a `CurriedFunction3` where the first argument is of type `T`? How do you use that in the example?

**Comment by tycho01** [comment]
You're combining things here; if `(val: T)` is already supplied, then the `T` no longer needs to be part of that `CurriedFunction` (so that can also go from 3 to 2). I reproduced this at the [TS Playground](https://www.typescriptlang.org/play/) now as follows:
```ts
interface CurriedFunction2<T1, T2, R> {
    (v1: T1): (v2: T2) => R;
    (v1: T1, v2: T2): R;
}

declare function propOr<T, U, K extends keyof U>(val: T): CurriedFunction2<K, U, U[K] | T>;

const alice = {
  age: 20,
  height: 160
};

const defaultZero = propOr(0); // function propOr<number, {}, never>(val: number): CurriedFunction2<never, {}, any>
const ageOrZero = defaultZero("age", alice); // Argument of type '"age"' is not assignable to parameter of type 'never'.
```

You'll notice the type already goes wrong during partial application. The problem here is that the generics are positioned as part of the first function, and as a result get evaluated upon this partial application, where the information needed to populate them is not yet available in the parameters (aside from `T`). That's unfortunate here, since `CurriedFunction` interfaces cannot hold the generics themselves.

There's another problem here though: `keyof` doesn't work well with currying, because the `K` generic depends on the `U` generic, which might not yet be available if one were to supply these two parameters separately.

However, it would still work if we were to supply those two together. In that case, we could just represent that part as a non-curried function here. In the above sample, swap out that definition for `propOr<T>(val: T): <U, K extends keyof U>(key: K, obj: U) => U[K] | T;`, and you'll find it type-checks. :)

**Comment by Ramblurr** [comment]
`propOr<T>(val: T): <U, K extends keyof U>(key: K, obj: U) => U[K] | T;` 

That indeed works for me.

**Comment by tycho01** [comment]
okay, pushed the edit :), thanks again for reporting the issue!
