### ISSUE TITLE
Extending set() types

### ISSUE THREAD

**Issue by bloadvenro** [types/npm-ramda#180]
Hello! :)

Currently we have:

```
set<T,U>(lens: Lens, a: U, obj: T): T;
set<U>(lens: Lens, a: U): <T>(obj: T) => T;
set(lens: Lens): <T,U>(a: U, obj: T) => T;
```
Is it possible to add also

```
set<T,U>(lens: Lens): (a: U) => (obj: T) => T;
set(lens: Lens): <T,U>(a: U) => (obj: T) => T;
```
Shortened сopy-paste from my use case (for `set<T,U>(lens: Lens): (a: U) => (obj: T) => T;`):

```
const setName = set<Specification.Shape, string>(lensProp('name'))

Container.of(specification)
  .map(setName('newName')) // mapper function then accepts the last argument of Specification.Shape type 
```

I changed my local copy of `index.d.ts` and it works well. Please correct me if I did something wrong.

Thank you for awesome work!

**Comment by tycho01** [comment]
Hey! Sorry for overlooking these currying variations; feel free to send a PR!

On the generics, for them to resolve correctly, each one should be delayed until its first occurrence, meaning rather than the two suggested forms, it should probably become like this: `set(lens: Lens): <U>(a: U) => <T>(obj: T) => T;`.

That said, I guess this just pointed out another short-coming in our typings here: since the `U` generic is only assigned (by `a`) yet not actually used, it's not currently adding value -- just making the typing look smarter. As such, until we find a way to better infer the result type, we can also just ditch the `U` generic for now and type `a` as `any`.

Moral of the story: things are still far from perfect. :)

**Comment by bloadvenro** [comment]
@tycho01 I'm sorry. I a little bit distracted you :) The original code I mentioned was from DefinitelyTyped repo, and it is different from the code presented in this repo. In `npm-ramda` repo I saw:

```
        /**
         * Returns the result of "setting" the portion of the given data structure focused by the given lens to the
         * given value.
         */
        // hard to mix cuz different generics

        // // key lens:
        // set<T, K extends keyof T>(lens: KeyLens<T,K>, a: T[K], obj: T): T;
        // set<T, K extends keyof T>(lens: KeyLens<T,K>, a: T[K]): (obj: T) => T;
        // set<T, K extends keyof T>(lens: KeyLens<T,K>): CurriedFunction2<T[K], T, T>;
        // // set<T, K extends keyof T>: CurriedFunction3<KeyLens<T,K>, T[K], T, T>;

        // regular lenses:

        // // smart approach, unreliable:
        // set<T,U>(lens: Lens<T,U>, a: U, obj: T): T;
        // set<T,U>(lens: Lens<T,U>, a: U): (obj: T) => T;
        // // set<T,U>(lens: Lens<T,U>): (a: U, obj: T) => T;
        // set<T,U>(lens: Lens<T,U>): CurriedFunction2<U, T, T>;
        // // set<T,U>: CurriedFunction3<Lens<T,U>, U, T, T>;

        // // // manually set lens; is this useful?
        // // set<T,U>(lens: ManualLens<U>, a: U, obj: T): T;
        // // set<U>(lens: ManualLens<U>, a: U): <T>(obj: T) => T;
        // // set<T,U>(lens: ManualLens<U>): CurriedFunction2<U,T,T>;
        // // // set<T,U>: CurriedFunction3<ManualLens<U>, U, T, T>;

        // // assume result type equal to input object:
        // set<T>(lens: UnknownLens, a: any, obj: T): T;
        // set<T>(lens: UnknownLens, a: any): (obj: T) => T;
        // // set<T>(lens: UnknownLens): (a: any, obj: T) => T;
        // set<T>(lens: UnknownLens): CurriedFunction2<any, T, T>;
        // // set<T>: CurriedFunction3<UnknownLens, any, T, T>;

        // // // old version, with value as an unbound generic; is this useful?
        // // set<T,U>(lens: UnknownLens, a: U, obj: T): T;
        // // set<T,U>(lens: UnknownLens, a: U): (obj: T) => T;
        // // set<T,U>(lens: UnknownLens): CurriedFunction2<U,T,T>;
        // // // set<T,U>: CurriedFunction3<UnknownLens, U, T, T>;
        // base
        set<T, U>(lens: Lens<T, U>, a: U, obj: T): T;
        set<T, U>(lens: Lens<T, U>, a: U):{
            (obj: T): T;
        };
        set<T, U>(lens: Lens<T, U>):{
            (a: U, obj: T): T;
            (a: U):{
                (obj: T): T;
            };
        };

        // unknow
        set<T>(lens: UnknownLens, a: any, obj: T): T;
        set(lens: UnknownLens, a: any):{
            <T>(obj: T): T;
        };
        set(lens: UnknownLens):{
            <T>(a: any, obj: T): T;
            (a: any):{
                <T>(obj: T): T;
            };
        };
```

It seems that this section

```
  set<T, U>(lens: Lens<T, U>):{
            (a: U, obj: T): T;
            (a: U):{
                (obj: T): T;
            };
        };
```
is appropriate for my case. So I removed `types/ramda` and installed `types/npm-ramda`. But I've got another problem:

```
/* Code below works well if I use `lens`: */
const nameLens = lens(prop('name'). assoc('name') // `lens` return type in context of set<T, U> is Lens<T, U>
const setName = set<Specification.Shape, string>(nameLens) // OK. No errors.

/*
 * Type error: Argument of type 'ManualLens<{}>' is not assignable to parameter of type   
 * 'Lens<Shape, string>'. Type '{}' is not assignable to type 'string'.
 * when I use `lensProp`:
 */
const setName = set<Specification.Shape, string>(lensProp('name'))
```

`lensProp` has following types:

```
lensProp<T>(prop: Prop): ManualLens<T>;
lensProp(prop: Prop): UnknownLens;
```

I'm not very smart in writing types :) But may `lensProp` technically have `lensProp<T, U>(prop: Prop): Lens<T, U>` signature?

**Comment by tycho01** [comment]
Whoops, I see. Looks like `set` was accidentally lacking `ManualLens`. Should be fixed now.

I originally created the different lens types so as to allow indicating the different stages of info available. Maybe that's complicating things; an alternative would be to just express `UnknownLens` (input and output not statically known) and `ManualLens` (output type statically known, manually specified) in terms of `Lens` (input and output both statically known).
That said, they do still provide some value over it -- since for the first two not all types are known upon creation of the lens, they instead allow you to dynamically specify the types when calling their `get` (/ just `()`) / `set`.
